main/urls.py
from main.views import *
from django.conf.urls import url
from main.views import submitform, remove_basket_field, submt_basket, refresh_basketline

urlpatterns = [
    url(r'^submitmsg/$', submitform, name='submitmsg'),
    url(r'^removeline/$', remove_basket_field, name='removeline'),
    url(r'^submit_basket/$', submt_basket, name='submt_basket'),
    url(r'^update_basket/$', refresh_basketline, name='update_basket'),
]

zapas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from oscar.app import application
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from main.views import home
urlpatterns = [
    # Examples:
    # url(r'^$', 'zapas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include(application.urls)),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root': settings.STATIC_ROOT}),
    url(r'^main/', include('main.urls',namespace='main')),
]

#urlpatterns+=staticfiles_urlpatterns()

apps/basket/models.py
from oscar.apps.basket.models import *  # noqa

apps/basket/views.py
import json

from django import shortcuts
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import redirect
from django.template import RequestContext
from django.template.loader import render_to_string
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.views.generic import FormView, View
from extra_views import ModelFormSetView

from oscar.apps.basket import signals
from oscar.core import ajax
from oscar.core.loading import get_class, get_classes, get_model
from oscar.core.utils import redirect_to_referrer, safe_referrer

Applicator = get_class('offer.utils', 'Applicator')
(BasketLineFormSet, BasketLineForm, AddToBasketForm, BasketVoucherForm,
 SavedLineFormSet, SavedLineForm) \
    = get_classes('basket.forms', ('BasketLineFormSet', 'BasketLineForm',
                                   'AddToBasketForm', 'BasketVoucherForm',
                                   'SavedLineFormSet', 'SavedLineForm'))
Repository = get_class('shipping.repository', ('Repository'))
OrderTotalCalculator = get_class(
    'checkout.calculators', 'OrderTotalCalculator')
BasketMessageGenerator = get_class('basket.utils', 'BasketMessageGenerator')


class BasketView(ModelFormSetView):
    model = get_model('basket', 'Line')
    basket_model = get_model('basket', 'Basket')
    formset_class = BasketLineFormSet
    form_class = BasketLineForm
    extra = 0
    can_delete = True
    template_name = 'basket/basket.html'

    def get_formset_kwargs(self):
        kwargs = super(BasketView, self).get_formset_kwargs()
        kwargs['strategy'] = self.request.strategy
        return kwargs

    def get_queryset(self):
        return self.request.basket.all_lines()

    def get_shipping_methods(self, basket):
        return Repository().get_shipping_methods(
            basket=self.request.basket, user=self.request.user,
            request=self.request)

    def get_default_shipping_method(self, basket):
        return Repository().get_default_shipping_method(
            basket=self.request.basket, user=self.request.user,
            request=self.request)

    def get_basket_warnings(self, basket):
        """
        Return a list of warnings that apply to this basket
        """
        warnings = []
        for line in basket.all_lines():
            warning = line.get_warning()
            if warning:
                warnings.append(warning)
        return warnings

    def get_upsell_messages(self, basket):
        offers = Applicator().get_offers(basket, self.request.user,
                                         self.request)
        applied_offers = list(basket.offer_applications.offers.values())
        msgs = []
        for offer in offers:
            if offer.is_condition_partially_satisfied(basket) \
                    and offer not in applied_offers:
                data = {
                    'message': offer.get_upsell_message(basket),
                    'offer': offer}
                msgs.append(data)
        return msgs

    def get_basket_voucher_form(self):
        """
        This is a separate method so that it's easy to e.g. not return a form
        if there are no vouchers available.
        """
        return BasketVoucherForm()

    def get_context_data(self, **kwargs):
        context = super(BasketView, self).get_context_data(**kwargs)
        context['voucher_form'] = self.get_basket_voucher_form()

        # Shipping information is included to give an idea of the total order
        # cost.  It is also important for PayPal Express where the customer
        # gets redirected away from the basket page and needs to see what the
        # estimated order total is beforehand.
        context['shipping_methods'] = self.get_shipping_methods(
            self.request.basket)
        method = self.get_default_shipping_method(self.request.basket)
        context['shipping_method'] = method
        shipping_charge = method.calculate(self.request.basket)
        context['shipping_charge'] = shipping_charge
        if method.is_discounted:
            excl_discount = method.calculate_excl_discount(self.request.basket)
            context['shipping_charge_excl_discount'] = excl_discount

        context['order_total'] = OrderTotalCalculator().calculate(
            self.request.basket, shipping_charge)
        context['basket_warnings'] = self.get_basket_warnings(
            self.request.basket)
        context['upsell_messages'] = self.get_upsell_messages(
            self.request.basket)

        if self.request.user.is_authenticated():
            try:
                saved_basket = self.basket_model.saved.get(
                    owner=self.request.user)
            except self.basket_model.DoesNotExist:
                pass
            else:
                saved_basket.strategy = self.request.basket.strategy
                if not saved_basket.is_empty:
                    saved_queryset = saved_basket.all_lines()
                    formset = SavedLineFormSet(strategy=self.request.strategy,
                                               basket=self.request.basket,
                                               queryset=saved_queryset,
                                               prefix='saved')
                    context['saved_formset'] = formset
        return context

    def get_success_url(self):
        return safe_referrer(self.request, 'basket:summary')

    def formset_valid(self, formset):
        # Store offers before any changes are made so we can inform the user of
        # any changes
        offers_before = self.request.basket.applied_offers()
        save_for_later = False

        # Keep a list of messages - we don't immediately call
        # django.contrib.messages as we may be returning an AJAX response in
        # which case we pass the messages back in a JSON payload.
        flash_messages = ajax.FlashMessages()

        for form in formset:
            if (hasattr(form, 'cleaned_data') and
                    form.cleaned_data['save_for_later']):
                line = form.instance
                if self.request.user.is_authenticated():
                    self.move_line_to_saved_basket(line)

                    msg = render_to_string(
                        'basket/messages/line_saved.html',
                        {'line': line})
                    flash_messages.info(msg)

                    save_for_later = True
                else:
                    msg = _("You can't save an item for later if you're "
                            "not logged in!")
                    flash_messages.error(msg)
                    return redirect(self.get_success_url())

        if save_for_later:
            # No need to call super if we're moving lines to the saved basket
            response = redirect(self.get_success_url())
        else:
            # Save changes to basket as per normal
            response = super(BasketView, self).formset_valid(formset)

        # If AJAX submission, don't redirect but reload the basket content HTML
        if self.request.is_ajax():
            # Reload basket and apply offers again
            self.request.basket = get_model('basket', 'Basket').objects.get(
                id=self.request.basket.id)
            self.request.basket.strategy = self.request.strategy
            Applicator().apply(self.request.basket, self.request.user,
                               self.request)
            offers_after = self.request.basket.applied_offers()

            for level, msg in BasketMessageGenerator().get_messages(
                    self.request.basket, offers_before, offers_after, include_buttons=False):
                flash_messages.add_message(level, msg)

            # Reload formset - we have to remove the POST fields from the
            # kwargs as, if they are left in, the formset won't construct
            # correctly as there will be a state mismatch between the
            # management form and the database.
            kwargs = self.get_formset_kwargs()
            del kwargs['data']
            del kwargs['files']
            if 'queryset' in kwargs:
                del kwargs['queryset']
            formset = self.get_formset()(queryset=self.get_queryset(),
                                         **kwargs)
            ctx = self.get_context_data(formset=formset,
                                        basket=self.request.basket)
            return self.json_response(ctx, flash_messages)

        BasketMessageGenerator().apply_messages(self.request, offers_before)

        return response

    def json_response(self, ctx, flash_messages):
        basket_html = render_to_string(
            'basket/partials/basket_content.html',
            RequestContext(self.request, ctx))
        payload = {
            'content_html': basket_html,
            'messages': flash_messages.as_dict()}
        return HttpResponse(json.dumps(payload),
                            content_type="application/json")

    def move_line_to_saved_basket(self, line):
        saved_basket, _ = get_model('basket', 'basket').saved.get_or_create(
            owner=self.request.user)
        saved_basket.merge_line(line)

    def formset_invalid(self, formset):
        flash_messages = ajax.FlashMessages()
        flash_messages.warning(_(
            "Your basket couldn't be updated. "
            "Please correct any validation errors below."))

        if self.request.is_ajax():
            ctx = self.get_context_data(formset=formset,
                                        basket=self.request.basket)
            return self.json_response(ctx, flash_messages)

        flash_messages.apply_to_request(self.request)
        return super(BasketView, self).formset_invalid(formset)


class BasketAddView(FormView):
    """

templates/basket/partials/basket_content.html
{% load i18n %}
{% load thumbnail %}
{% load currency_filters %}
{% load purchase_info_tags %}
{% load widget_tweaks %}

{% if basket_warnings %}
    <h5>{% trans "Important messages about items in your basket" %}</h5>
    {% for warning in basket_warnings %}
        <div class="alert">{{ warning }}</div>
    {% endfor %}
{% endif %}

{% if upsell_messages %}
    <div class="well">
        <h3>{% trans "You could be missing out on offers!" %}</h3>
        {% for upsell in upsell_messages %}
            {% blocktrans with message=upsell.message url=upsell.offer.get_absolute_url offer_name=upsell.offer.name %}
                <div class="warning">{{ message }} to qualify for the <a href="{{ url }}">{{ offer_name }}</a> special offer</div>
            {% endblocktrans %}
        {% endfor %}
    </div>
{% endif %}

{% if not basket.is_empty %}
    {% block basket_form_headers %}
        <div class="basket-title hidden-xs">
            <div class="row">
                <h2 class="col-sm-6 h3">{% trans "Items to buy now" %}</h2>
                <p class="col-sm-3 h3">{% trans "Quantity" %}</p>
                <p class="col-sm-1 h3 align-right">{% trans "Price" %}</p>
                <p class="col-sm-2 h3 align-right">{% trans "Total" %}</p>
            </div>
        </div>
    {% endblock %}

    {% block basket_form_main %}
        <form action="." method="post" class="basket_summary" id="basket_formset">
            {% csrf_token %}
            {{ formset.management_form }}

            {% for form in formset %}
                {% with line=form.instance product=form.instance.product %}
                    {% purchase_info_for_line request line as session %}
                    <div class="basket-items">
                        <div class="row">
                            <div class="col-sm-2">
                                {{ form.id }}
                                {% with image=product.primary_image %}
                                    {% thumbnail image.original "100x100" upscale=False as thumb %}
                                        <a href="{{ product.get_absolute_url }}">
                                            <img class="thumbnail" src="{{ thumb.url }}" alt="{{ product.get_title }}"/>
                                        </a>
                                    {% endthumbnail %}
                                {% endwith %}
                            </div>
                            <div class="col-sm-4">
                                <h3><a href="{{ product.get_absolute_url }}">{{ line.description }}</a></h3>
                                <p class="availability {{ session.availability.code }}">{{ session.availability.message }}</p>
                            </div>
                            <div class="col-sm-3">
                                <div class="checkout-quantity">
                                    <div class="input-group  {% if form.errors %}error{% endif %}">
                                        {% render_field form.quantity class+="form-control" %}
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit" data-loading-text="{% trans 'Updating...' %}">{% trans "Update" %}</button>
                                    </span>
                                    </div>
                                </div>
                                    <div>
                                        <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="remove" class="inline">{% trans "Remove" %}</a>
                                        {% if user.is_authenticated %}
                                            | <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="save" class="inline">{% trans "Save for later" %}</a>
                                        {% endif %}
                                        <div style="display:none">
                                            {{ form.save_for_later }}
                                            {{ form.DELETE }}
                                        </div>
                                        {% for field_errors in form.errors.values %}
                                            {% for error in field_errors %}
                                                <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                                            {% endfor %}

                                        {% endfor %}
                                    </div>

                            </div>
                            <div class="col-sm-1">
                                <p class="price_color align-right">
                                    {% if line.is_tax_known %}
                                        {{ line.unit_price_incl_tax|currency:line.price_currency }}
                                    {% else %}
                                        {{ line.unit_price_excl_tax|currency:line.price_currency }}
                                    {% endif %}
                                </p>
                            </div>
                            <div class="col-sm-2">
                                <p class="price_color align-right">
                                    {% if line.is_tax_known %}
                                        {{ line.line_price_incl_tax|currency:line.price_currency }}
                                    {% else %}
                                        {{ line.line_price_excl_tax|currency:line.price_currency }}
                                    {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                {% endwith %}
            {% endfor %}
        </form>
    {% endblock %}

    <div class="row">
        {% block vouchers %}
            {# Hide the entire section if a custom BasketView doesn't pass in a voucher form #}
            {% if voucher_form %}
                <div class="col-sm-6">
                    <div class="sub-header">
                        <h2>{% trans "Voucher/promo code" %}</h2>
                    </div>
                    <p id="voucher_form_link"><a href="#voucher" class="btn btn-default btn-full">{% trans "I have a voucher code..." %}</a></p>

                    <div id="voucher_form_container" style="display:none">
                        <form id="voucher_form" action="{% url 'basket:vouchers-add' %}" method="post">
                            {% csrf_token %}
                            {% include "partials/form_fields.html" with form=voucher_form %}
                            <button type="submit" class="btn btn-info" data-loading-text="{% trans 'Adding...' %}">{% trans "Add voucher" %}</button>
                            {% trans "or" %} <a href="#" id="voucher_form_cancel">{% trans "cancel" %}</a>
                        </form>
                    </div>
                </div>
            {% endif %}
        {% endblock vouchers %}

        {% block baskettotals %}
            <div class="col-sm-6">
                <div class="sub-header">
                    <h2>{% trans "Totals" %}</h2>
                </div>
                {% include 'basket/partials/basket_totals.html' with editable=1 %}
            </div>
        {% endblock baskettotals %}
    </div>


    {% block formactions %}
        <div class="form-group clearfix">
            <div class="row">
                <div class="col-sm-4 col-sm-offset-8">
                    <a href="{% url 'checkout:index' %}" class="btn btn-lg btn-primary btn-block">{% trans "Proceed to checkout" %}</a>
                </div>
            </div>
        </div>
    {% endblock formactions %}

{% else %}
    {% block emptybasket %}
        <p>
            {% trans "Your basket is empty." %}
            <a href="{{ homepage_url }}">{% trans "Continue shopping" %}</a>
        </p>
    {% endblock %}
{% endif %}

{% block savedbasket %}
    {% if user.is_authenticated and saved_formset %}
        <div class="well">
            <div class="sub-header">
                <h2>{% trans "Items to buy later" %}</h2>
            </div>
            <div class="row basket-title hidden-xs">
                <p class="col-sm-8 h4">{% trans "Items" %}</p>
                <p class="col-sm-2 h4 align-center">{% trans "Price" %}</p>
                <div class="col-sm-2">&nbsp;</div>
            </div>
            <form action="{% url 'basket:saved' %}" method="post" class="form-stacked later_summary" id="saved_basket_formset">
                {% csrf_token %}
                {{ saved_formset.management_form }}
                {% for form in saved_formset %}
                    {% purchase_info_for_product request form.instance.product as session %}
                    <div class="basket-items">
                        <div class="row">
                            <div class="col-sm-2">
                                {{ form.id }}
                                {% with image=form.instance.product.primary_image %}
                                    {% thumbnail image.original "100x100" upscale=False as thumb %}
                                        <a href="{{ form.instance.product.get_absolute_url }}">
                                            <img class="thumbnail" src="{{ thumb.url }}" alt="{{ form.instance.product.get_title }}">
                                        </a>
                                    {% endthumbnail %}
                                {% endwith %}
                            </div>
                            <div class="col-sm-6">
                                <h3><a href="{{ form.instance.product.get_absolute_url }}">{{ form.instance.description }}</a></h3>
                                <p class="availability {{ session.availability.code }}">{{ session.availability.message }}</p>
                                <a href="#" data-id="{{ forloop.counter0 }}" data-behaviours="remove">{% trans "Remove" %}</a>
                                <div style="display:none">
                                    {{ form.move_to_basket }}
                                    {{ form.DELETE }}
                                </div>
                            </div>
                            {% purchase_info_for_product request form.instance.product as saved %}
                            <div class="col-sm-2 align-center">
                                <p class="price_color">
                                    {% if saved.price.is_tax_known %}
                                        {{ saved.price.incl_tax|currency:saved.price.currency }}
                                    {% else %}
                                        {{ saved.price.excl_tax|currency:saved.price.currency }}
                                    {% endif %}
                                </p>
                            </div>
                            <div class="col-sm-2">
                                <a href="#" data-id="{{ forloop.counter0 }}" class="btn pull-right btn-block" data-behaviours="move">{% trans "Move to basket" %}</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </form>
        </div>
    {% endif %}
{% endblock %}

templates/basket/partials/basket_quick.html
{% load history_tags %}
{% load basket_tags %}
{% load currency_filters %}
{% load thumbnail %}
{% load i18n %}
{% load staticfiles %}
{% load shopelement %}

<div class="basket-mini-content">
<form class="basket-mini-item list-unstyled" action="/basket/" method="post" id="basket_formset">

    <p class="cart-h">Корзина покупок</p>
    {% if request.basket.num_lines %}
        {% for line in request.basket.all_lines %}

                <div class="row">
                    <div class="col-sm-2">
                        <div class="image_container">
                            {% with image=line.product.parent.primary_image %}
                                {% thumbnail image.original "100x100" crop="center" upscale=False as thumb %}
                                <img class="thumbnail" src="{{ thumb.url }}" alt="{{ line.product.get_title }}">
                                {% endthumbnail %}
                            {% endwith %}
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <p><a href="{{ line.product.get_absolute_url }}">{{ line.description }}</a></p>
                    </div>
                    <div class="col-sm-2 align-center"><p class="mini-text">количество</p><input type="number" id="id_form-{{ forloop.counter0 }}-quantity" value="{{ line.quantity }}"><a href="#" class="update_item vertical-middle-align" data-behaviours="update" data-count="{{ forloop.counter0 }}" data-id="{{ line.id }}">Обновить</a></div>
                    <div class="col-sm-2 price_color align-right"><strong class="vertical-middle-align">{{ line.line_price_excl_tax|currency:request.basket.currency }}</strong> <div class="helper"></div></div>
                    <div class="col-sm-1 price_color align-right"><a href="#" class="remove_item vertical-middle-align" data-behaviours="remove" data-id="{{ line.id }}"><img src="{% static 'img/delete.png' %}"></a><input style="display: none;" id="id_form-{{ forloop.counter0 }}-DELETE" name="form-{{ forloop.counter0 }}-DELETE" type="checkbox"><p class="helper"></p></div>
                </div>

        {% endfor %}
        <!--
        <div class="form-group form-actions">
            <p class="align-right">
                {% if request.basket.is_tax_known %}
                    <small>{% trans "Total:" %} {{ request.basket.total_incl_tax|currency:request.basket.currency }}</small>
                {% else %}
                    <small>{% trans "Total:" %} {{ request.basket.total_excl_tax|currency:request.basket.currency }}</small>
                {% endif %}
            </p>
            <a href="{% url 'basket:summary' %}" class="btn btn-info btn-sm">{% trans "View basket" %}</a>
            <a href="{% url 'checkout:index' %}" class="btn btn-primary btn-sm pull-right"><i class="icon-shopping-cart"></i> {% trans "Checkout" %}</a>
        </div>
    {% else %}
        <li><p>{% trans "Your basket is empty." %}</p></li>
    {% endif %}
    -->
</form>
<script src="{% static 'js/oscar/ui.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.remove_item').click(function () {
            var line = $(this).attr('data-id');
            $.ajax({
                type:'GET',
                url:'{% url "main:removeline" %}',
                data:{'line':line},
                success:function (msg) {
                    $("#basket_content").html(msg);

                }
            })
        });
        $('.update_item').click(function () {
            var line = $(this).attr('data-id');
            var count = $(this).attr('data-count');
            var quantity = $('#id_form-'+count+'-quantity').val();
            $.ajax({
                type:'GET',
                url:'{% url "main:update_basket" %}',
                data:{'line':line,'quantity':quantity },
                success:function (msg) {
                    $("#basket_content").html(msg);
                }
            })
        })
    })
</script>
{% deliveryform %}
</div>